AllCops:
  # TargetRubyVersion: 2.4
  TargetRubyVersion: 2.2.2

  DisplayCopNames: true
  DisplayStyleGuide: true

AsciiComments:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PredicateName:
  NameWhitelist:
    - is_a?

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/AlignParameters:
  Enabled: false

LineLength:
  Max: 120

Lint/UnifiedInteger:
  Description: 'Use Integer instead of Fixnum or Bignum'
  Enabled: false
